- name: Configuring redis
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo  #we haven't used remote_src:yes bcoz we copying from loacal(ansible)  

- name: Installing redis
  ansible.builtin.package:
    name: redis-6.2.11
    state: present

- name: Updating the redis config
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDb service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true















