- name: Configuring MongoDB
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo  #we haven't used remote_src:yes bcoz we copying from loacal(ansible)  

- name: Installing mongDB
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Updateing the mongoDB config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting the MongoDb service
  ansible.builtin.systemd:
    name: mongodb-org 
    state: started
    enabled: true
















