- name: Demo on vars
  hosts: all
  vars:
    URL: play.google.global.com     #in that URL is given at the play level it's called global variable its can used across the playbook
  tasks:
    - name: Priniting the value of varible
      ansible.builtin.debug:
        msg: Value of the {{ URL }}

    - name: Demo for local variable
      ansible.builtin.debug:
        msg: Value of the {{ URL }}
      vars:                              
        URL: play.google.local.com      # this vars (URl)given at the task level so its an local varaible

    - name: Demo for commad line variable
      ansible.builtin.debug:
        msg: Value of the {{ CARNAME }}

    - name: Demo for double from stating line line variable
      ansible.builtin.debug:
        msg: "{{ CARNAME }}""


# Local vars has higher than the global
# and command line vars has more prefernce that both ...Command line vars are nothing but the passing vars from excuting at the taks level
# Begining of the line you need to pass the vars with  EX"{{ CARNAME }}"