- name: Demo on register 
  hosts: all
  tasks:
    - name: Demo on shell
      ansible.builtin.shell: uptime
      register: OUT

    - name: Printing output variable
      ansible.builtin.debug: 
        msg: "{{OUT}}""