- name: Demo on privilage esclations
  hosts: all
  become: yes        # using this we run the playbook as sudo
  tasks:
    - name: User ID
      ansible.builtin.shell: id
      register: OUT

    - name: User details print
      ansible.builtin.debug:
        msg: "{{ OUT.stdout }}"