- name: Play1
  hosts: all
  tasks:
    - name: Install ntpdate
      ansible.builtin.package:
        name: ntpdate             # it's a package name you want to install
        state: present        # Present means install ,Absent is uninstall,lates it to update




