- name: Play1
  hosts: all
  become: yes   # using this we are taking root privilages
  tasks: 
    - name: Install nginx
      ansible.builtin.package:
        name: nginx             # it's a package name you want to install
        state: present        # Present means install ,Absent is uninstall,lates it to update

    - name: install wget
      ansible.builtin.debug:
        name: wget
        state: wget


