- name: Demo on using register 
  hosts: all
  tasks:
    - name: Demo on using shell
      ansible.builtin.shell: uptime
      register: OUT

    - name: Printing output variable
      ansible.builtin.debug: 
        msg: "{{OUT}}""