- name: Creating the app user {{ COMPONENT }}-{{ENV}} server
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment:  Application user
  register: OUT

- name: Just printing the output 
  ansible.builtin.debug: 
    msg: "{{OUT}}"