- name: Installing maven {{COMPONENT}}- {{ENV}} server
  ansible.builtin.package:
    name: maven
    state: present

- name: Creating the app user
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Generarating {{COMPONENT}} artifact
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc 


- name: Configuring the node repo 
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}