- name: Installing maven {{COMPONENT}}- {{ENV}} server
  ansible.builtin.package:
    name: maven
    state: present

- name: Creating the app user
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and extract {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Generarating {{COMPONENT}} artifact
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdie: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Copying the systemd files
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/service/system/{{COMPONENT}}.service


- name: Restarting the {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: true
    daemon_reload: true
